### ISSUE TITLE
data_munger.rb:367:in `convert_legacy_driver_format_at!': undefined method `key?' for #<Array:0x00000000fa9f10> (NoMethodError)

### ISSUE THREAD

**Issue by boldandbusted** [neillturner/kitchen-softlayer#2]
``` shell
jesse@fuji-02 Wed Jan 20 18:10:23                                                                                                                                          
$ kitchen create
-----> Starting Kitchen (v1.4.2)
/home/jesse/.rvm/gems/ruby-2.2.2/gems/test-kitchen-1.4.2/lib/kitchen/data_munger.rb:367:in `convert_legacy_driver_format_at!': undefined method `key?' for #<Array:0x00000000fa9f10> (NoMethodError)
        from /home/jesse/.rvm/gems/ruby-2.2.2/gems/test-kitchen-1.4.2/lib/kitchen/data_munger.rb:352:in `block in convert_legacy_driver_format!'
        from /home/jesse/.rvm/gems/ruby-2.2.2/gems/test-kitchen-1.4.2/lib/kitchen/data_munger.rb:351:in `each'
        from /home/jesse/.rvm/gems/ruby-2.2.2/gems/test-kitchen-1.4.2/lib/kitchen/data_munger.rb:351:in `convert_legacy_driver_format!'
        from /home/jesse/.rvm/gems/ruby-2.2.2/gems/test-kitchen-1.4.2/lib/kitchen/data_munger.rb:44:in `initialize'
        from /home/jesse/.rvm/gems/ruby-2.2.2/gems/test-kitchen-1.4.2/lib/kitchen/config.rb:145:in `new'
        from /home/jesse/.rvm/gems/ruby-2.2.2/gems/test-kitchen-1.4.2/lib/kitchen/config.rb:145:in `data'
        from /home/jesse/.rvm/gems/ruby-2.2.2/gems/test-kitchen-1.4.2/lib/kitchen/config.rb:124:in `suites'
        from /home/jesse/.rvm/gems/ruby-2.2.2/gems/test-kitchen-1.4.2/lib/kitchen/config.rb:175:in `filter_instances'
        from /home/jesse/.rvm/gems/ruby-2.2.2/gems/test-kitchen-1.4.2/lib/kitchen/config.rb:134:in `build_instances'
        from /home/jesse/.rvm/gems/ruby-2.2.2/gems/test-kitchen-1.4.2/lib/kitchen/config.rb:110:in `instances'
        from /home/jesse/.rvm/gems/ruby-2.2.2/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:115:in `filtered_instances'
        from /home/jesse/.rvm/gems/ruby-2.2.2/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:145:in `parse_subcommand'
        from /home/jesse/.rvm/gems/ruby-2.2.2/gems/test-kitchen-1.4.2/lib/kitchen/command/action.rb:38:in `block in call'
        from /home/jesse/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/benchmark.rb:288:in `measure'
        from /home/jesse/.rvm/gems/ruby-2.2.2/gems/test-kitchen-1.4.2/lib/kitchen/command/action.rb:37:in `call'
        from /home/jesse/.rvm/gems/ruby-2.2.2/gems/test-kitchen-1.4.2/lib/kitchen/cli.rb:56:in `perform'
        from /home/jesse/.rvm/gems/ruby-2.2.2/gems/test-kitchen-1.4.2/lib/kitchen/cli.rb:171:in `block (2 levels) in <class:CLI>'
        from /home/jesse/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/jesse/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/jesse/.rvm/gems/ruby-2.2.2/gems/test-kitchen-1.4.2/lib/kitchen/cli.rb:308:in `invoke_task'
        from /home/jesse/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /home/jesse/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /home/jesse/.rvm/gems/ruby-2.2.2/gems/test-kitchen-1.4.2/bin/kitchen:13:in `block in <top (required)>'
        from /home/jesse/.rvm/gems/ruby-2.2.2/gems/test-kitchen-1.4.2/lib/kitchen/errors.rb:154:in `with_friendly_errors'
        from /home/jesse/.rvm/gems/ruby-2.2.2/gems/test-kitchen-1.4.2/bin/kitchen:13:in `<top (required)>'
        from /home/jesse/.rvm/gems/ruby-2.2.2/bin/kitchen:23:in `load'
        from /home/jesse/.rvm/gems/ruby-2.2.2/bin/kitchen:23:in `<main>'
        from /home/jesse/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
jesse@fuji-02 Wed Jan 20 18:12:11                                                                                                                                          
$ vagrant -v
Vagrant 1.7.2
jesse@fuji-02 Wed Jan 20 18:12:14                                                                                                                                          
$ kitchen -v
Test Kitchen version 1.4.2
```

I don't know if this is an issue with this repo's code, or the main test-kitchen. Please let me know if I'm barking up the wrong tree! :) Thank you.

**Comment by neillturner** [comment]
My code is not in the trace so i don't think it is directly my code but it could be the parameters specfied in the .kitchen.yml file. The code in question is recursive merging of configuration between platforms, suites, and common data from the .kitchen.yml file.  
 you can do a few things to help debugging: 
1. add a '-l debug' to the end of your kitchen command. 
2. run kitchen diagnose  to see the structure of your .kitchen.yml file
3. simply the .kitchen.yml file. You might be able to workaround the issue. 
4. put some ruby puts in the code to see what is happening.

**Comment by boldandbusted** [comment]
Thank you for the troubleshooting tips! :)

**Comment by neillturner** [comment]
closing. no further activity.

**Comment by forzagreen** [comment]
I had a similar issue. The problem was actually in my `.kitchen.yml` file's syntax.
